### PR TITLE
This code is probably awful. But it works.

### PR DESCRIPTION
**Pull request by duner**
LXML is bad.

### CODE REVIEW

**Comment by scott2b** [comment]
Why is lxml bad? lxml is awesome. It can be a pita to manage as a dependency sometimes, but since we are using configuration management, this should really be a non-issue. I don't really see anybody offering up a strong alternative to lxml.

**Comment by JoeGermuska** [comment]
Guessing it's more a distaste for xpath expressions, but I can't speak for @duner. It's also the case that a lot of the time the raw DOM API is just ugly, and it would be nice to do things more pythonically, but… 
¯\ _(ツ)_/¯

**Comment by scott2b** [comment]
Ah ok. I guess most of my love for lxml comes from using with cssselect, which is pretty much exclusively how I tend to use it. If you are just doing xml parsing and dom manipulation, then I suppose there are in fact other options. But if it works ....

**Comment by duner** [comment]
Maybe it's not that lxml is bad, I just found it to be poorly documented, so I was kinda flailing a bit trying to get it to do what I'm trying to do. I'm used to Beautiful Soup (though I guess that only does DOM parsing, not manipulation).

**Comment by duner** [comment]
Anyway, @JoeGermuska, can I go ahead and pull this into master?

**Comment by JoeGermuska** [comment]
no sir, i'll take care of that ;)

**Pull request merged**
